#!/usr/bin/env ruby
# Amahi Home Server
# Copyright (C) 2007-2010 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

require File.dirname(__FILE__) + '/../config/boot'

# send warnings to the bit bucket
$stderr.reopen("/dev/null", "w")

ENV["RAILS_ENV"] = (ENV['RAILS_ENV'] || "production").dup
RAILS_ENV.replace(ENV['RAILS_ENV']) if defined?(RAILS_ENV)

# full RoR environment!
require File.dirname(__FILE__) + '/../config/environment'
ROOTDIR = File.join(File.dirname(__FILE__), "..")

def main
	begin
		puts User.admins.first.login
	rescue => e
		puts "error, cannot find any admin user. sorry."
	end
end

main
